-- MySQL Script generated by MySQL Workbench
-- Wed Mar 12 21:36:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema titulacion
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `titulacion` ;

-- -----------------------------------------------------
-- Schema titulacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `titulacion` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `titulacion` ;

-- -----------------------------------------------------
-- Table `titulacion`.`actos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`actos` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`actos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `modalidad` ENUM('virtual', 'Presencial') NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `lugar` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`docentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`docentes` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`docentes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `apellido_paterno` VARCHAR(255) NOT NULL,
  `apellido_materno` VARCHAR(255) NOT NULL,
  `cedula_profesional` VARCHAR(255) NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  `profesion` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`acto_docentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`acto_docentes` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`acto_docentes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `acto_id` BIGINT UNSIGNED NOT NULL,
  `docente_id` BIGINT UNSIGNED NOT NULL,
  `sinodal` ENUM('presidente', 'secretario', 'Suplente') NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `acto_docentes_acto_id_foreign` (`acto_id` ASC) VISIBLE,
  INDEX `acto_docentes_docente_id_foreign` (`docente_id` ASC) VISIBLE,
  CONSTRAINT `acto_docentes_acto_id_foreign`
    FOREIGN KEY (`acto_id`)
    REFERENCES `titulacion`.`actos` (`id`),
  CONSTRAINT `acto_docentes_docente_id_foreign`
    FOREIGN KEY (`docente_id`)
    REFERENCES `titulacion`.`docentes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`administrativos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`administrativos` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`administrativos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `apellido_paterno` VARCHAR(255) NOT NULL,
  `apellido_materno` VARCHAR(255) NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  `puesto` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`carreras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`carreras` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`carreras` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `clave` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`plan_estudios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`plan_estudios` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`plan_estudios` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NOT NULL,
  `numero_creditos` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`comites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`comites` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`comites` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `plan_estudios_id` BIGINT UNSIGNED NOT NULL,
  `especificacion` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `comites_plan_estudios_id_foreign` (`plan_estudios_id` ASC) VISIBLE,
  CONSTRAINT `comites_plan_estudios_id_foreign`
    FOREIGN KEY (`plan_estudios_id`)
    REFERENCES `titulacion`.`plan_estudios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`comite_docentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`comite_docentes` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`comite_docentes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comite_id` BIGINT UNSIGNED NOT NULL,
  `docente_id` BIGINT UNSIGNED NOT NULL,
  `cargo` ENUM('asesor', 'revisor') NOT NULL DEFAULT 'asesor',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `comite_docentes_comite_id_foreign` (`comite_id` ASC) VISIBLE,
  INDEX `comite_docentes_docente_id_foreign` (`docente_id` ASC) VISIBLE,
  CONSTRAINT `comite_docentes_comite_id_foreign`
    FOREIGN KEY (`comite_id`)
    REFERENCES `titulacion`.`comites` (`id`),
  CONSTRAINT `comite_docentes_docente_id_foreign`
    FOREIGN KEY (`docente_id`)
    REFERENCES `titulacion`.`docentes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`egresados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`egresados` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`egresados` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `apellido_paterno` VARCHAR(255) NOT NULL,
  `apellido_materno` VARCHAR(255) NOT NULL,
  `numero_control` VARCHAR(255) NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(255) NOT NULL,
  `carrera_id` BIGINT UNSIGNED NOT NULL,
  `plan_estudio_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `egresados_carrera_id_foreign` (`carrera_id` ASC) VISIBLE,
  INDEX `egresados_plan_estudio_id_foreign` (`plan_estudio_id` ASC) VISIBLE,
  CONSTRAINT `egresados_carrera_id_foreign`
    FOREIGN KEY (`carrera_id`)
    REFERENCES `titulacion`.`carreras` (`id`),
  CONSTRAINT `egresados_plan_estudio_id_foreign`
    FOREIGN KEY (`plan_estudio_id`)
    REFERENCES `titulacion`.`plan_estudios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`documento_solicitudes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`documento_solicitudes` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`documento_solicitudes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ruta` VARCHAR(255) NOT NULL,
  `validacion` ENUM('pendiente', 'aceptado', 'rechazado') NOT NULL DEFAULT 'pendiente',
  `plan_estudios-id` BIGINT UNSIGNED NOT NULL,
  `egresado_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `documento_solicitudes_plan_estudios_id_foreign` (`plan_estudios-id` ASC) VISIBLE,
  INDEX `documento_solicitudes_egresado_id_foreign` (`egresado_id` ASC) VISIBLE,
  CONSTRAINT `documento_solicitudes_egresado_id_foreign`
    FOREIGN KEY (`egresado_id`)
    REFERENCES `titulacion`.`egresados` (`id`),
  CONSTRAINT `documento_solicitudes_plan_estudios_id_foreign`
    FOREIGN KEY (`plan_estudios-id`)
    REFERENCES `titulacion`.`plan_estudios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`titulacion_opciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`titulacion_opciones` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`titulacion_opciones` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `tiempo_maximo` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`opcion_requisitos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`opcion_requisitos` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`opcion_requisitos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `opcion_titulacion_id` BIGINT UNSIGNED NOT NULL,
  `documento_requerido` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `tipo` ENUM('PDF', 'Imagen', 'Fotografia') NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `opcion_requisitos_opcion_titulacion_id_foreign` (`opcion_titulacion_id` ASC) VISIBLE,
  CONSTRAINT `opcion_requisitos_opcion_titulacion_id_foreign`
    FOREIGN KEY (`opcion_titulacion_id`)
    REFERENCES `titulacion`.`titulacion_opciones` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`tramites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`tramites` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`tramites` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `egresado_id` BIGINT UNSIGNED NOT NULL,
  `titulacion_opciones_id` BIGINT UNSIGNED NOT NULL,
  `nombre_proyecto` VARCHAR(255) NOT NULL,
  `liberacion` ENUM('aceptado', 'rechazado', 'pendiente') NOT NULL DEFAULT 'pendiente',
  `status` ENUM('iniciado', 'rechazado', 'pendiente') NOT NULL DEFAULT 'iniciado',
  `paso` ENUM('iniciado', 'rechazado', 'pendiente') NOT NULL DEFAULT 'iniciado',
  `observaciones` VARCHAR(255) NOT NULL DEFAULT 'pendiente',
  `pago` ENUM('aceptado', 'pendiente') NOT NULL DEFAULT 'pendiente',
  `comite_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `acto_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `tramites_egresado_id_foreign` (`egresado_id` ASC) VISIBLE,
  INDEX `tramites_titulacion_opciones_id_foreign` (`titulacion_opciones_id` ASC) VISIBLE,
  INDEX `tramites_comite_id_foreign` (`comite_id` ASC) VISIBLE,
  INDEX `tramites_acto_id_foreign` (`acto_id` ASC) VISIBLE,
  CONSTRAINT `tramites_acto_id_foreign`
    FOREIGN KEY (`acto_id`)
    REFERENCES `titulacion`.`actos` (`id`),
  CONSTRAINT `tramites_comite_id_foreign`
    FOREIGN KEY (`comite_id`)
    REFERENCES `titulacion`.`comites` (`id`),
  CONSTRAINT `tramites_egresado_id_foreign`
    FOREIGN KEY (`egresado_id`)
    REFERENCES `titulacion`.`egresados` (`id`),
  CONSTRAINT `tramites_titulacion_opciones_id_foreign`
    FOREIGN KEY (`titulacion_opciones_id`)
    REFERENCES `titulacion`.`titulacion_opciones` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`documento_titulaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`documento_titulaciones` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`documento_titulaciones` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ruta` VARCHAR(255) NOT NULL,
  `validacion` ENUM('pendiente', 'aceptado', 'rechazado') NOT NULL DEFAULT 'pendiente',
  `opcion_requisito_id` BIGINT UNSIGNED NOT NULL,
  `tramite_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `documento_titulaciones_opcion_requisito_id_foreign` (`opcion_requisito_id` ASC) VISIBLE,
  INDEX `documento_titulaciones_tramite_id_foreign` (`tramite_id` ASC) VISIBLE,
  CONSTRAINT `documento_titulaciones_opcion_requisito_id_foreign`
    FOREIGN KEY (`opcion_requisito_id`)
    REFERENCES `titulacion`.`opcion_requisitos` (`id`),
  CONSTRAINT `documento_titulaciones_tramite_id_foreign`
    FOREIGN KEY (`tramite_id`)
    REFERENCES `titulacion`.`tramites` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`especialidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`especialidades` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`especialidades` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`especialidad_plan_estudios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`especialidad_plan_estudios` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`especialidad_plan_estudios` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `especialidad_id` BIGINT UNSIGNED NOT NULL,
  `plan_estudio_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `especialidad_plan_estudios_especialidad_id_foreign` (`especialidad_id` ASC) VISIBLE,
  INDEX `especialidad_plan_estudios_plan_estudio_id_foreign` (`plan_estudio_id` ASC) VISIBLE,
  CONSTRAINT `especialidad_plan_estudios_especialidad_id_foreign`
    FOREIGN KEY (`especialidad_id`)
    REFERENCES `titulacion`.`especialidades` (`id`),
  CONSTRAINT `especialidad_plan_estudios_plan_estudio_id_foreign`
    FOREIGN KEY (`plan_estudio_id`)
    REFERENCES `titulacion`.`plan_estudios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`failed_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`failed_jobs` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`failed_jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`migrations` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`migrations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`password_reset_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`password_reset_tokens` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`password_reset_tokens` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`personal_access_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`personal_access_tokens` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`personal_access_tokens` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable_type` VARCHAR(255) NOT NULL,
  `tokenable_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  `abilities` TEXT NULL DEFAULT NULL,
  `last_used_at` TIMESTAMP NULL DEFAULT NULL,
  `expires_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `personal_access_tokens_token_unique` (`token` ASC) VISIBLE,
  INDEX `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type` ASC, `tokenable_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`plan_estudios_titulacion_opciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`plan_estudios_titulacion_opciones` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`plan_estudios_titulacion_opciones` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `plan_estudios_id` BIGINT UNSIGNED NOT NULL,
  `titulacion_opcion_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `plan_estudios_titulacion_opciones_plan_estudios_id_foreign` (`plan_estudios_id` ASC) VISIBLE,
  INDEX `plan_estudios_titulacion_opciones_titulacion_opcion_id_foreign` (`titulacion_opcion_id` ASC) VISIBLE,
  CONSTRAINT `plan_estudios_titulacion_opciones_plan_estudios_id_foreign`
    FOREIGN KEY (`plan_estudios_id`)
    REFERENCES `titulacion`.`plan_estudios` (`id`),
  CONSTRAINT `plan_estudios_titulacion_opciones_titulacion_opcion_id_foreign`
    FOREIGN KEY (`titulacion_opcion_id`)
    REFERENCES `titulacion`.`titulacion_opciones` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`plan_requisitos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`plan_requisitos` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`plan_requisitos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `plan_estudio_id` BIGINT UNSIGNED NOT NULL,
  `documento_requerido` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `tipo` ENUM('PDF', 'Imagen', 'Fotografia') NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `plan_requisitos_plan_estudio_id_foreign` (`plan_estudio_id` ASC) VISIBLE,
  CONSTRAINT `plan_requisitos_plan_estudio_id_foreign`
    FOREIGN KEY (`plan_estudio_id`)
    REFERENCES `titulacion`.`plan_estudios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`users` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`usuarios` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `actual_type` VARCHAR(255) NOT NULL,
  `actual_id` BIGINT UNSIGNED NOT NULL,
  `nombre_usuario` VARCHAR(255) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `expiracion` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuarios_nombre_usuario_unique` (`nombre_usuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`validacion_solicitudes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`validacion_solicitudes` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`validacion_solicitudes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ruta` VARCHAR(255) NOT NULL,
  `validacion` ENUM('pendiente', 'aceptado', 'rechazado') NOT NULL,
  `documento_solicitud_id` BIGINT UNSIGNED NOT NULL,
  `egresado_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `validacion_solicitudes_documento_solicitud_id_foreign` (`documento_solicitud_id` ASC) VISIBLE,
  INDEX `validacion_solicitudes_egresado_id_foreign` (`egresado_id` ASC) VISIBLE,
  CONSTRAINT `validacion_solicitudes_documento_solicitud_id_foreign`
    FOREIGN KEY (`documento_solicitud_id`)
    REFERENCES `titulacion`.`documento_solicitudes` (`id`),
  CONSTRAINT `validacion_solicitudes_egresado_id_foreign`
    FOREIGN KEY (`egresado_id`)
    REFERENCES `titulacion`.`egresados` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `titulacion`.`validacion_titulaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titulacion`.`validacion_titulaciones` ;

CREATE TABLE IF NOT EXISTS `titulacion`.`validacion_titulaciones` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `documento_titulacion_id` BIGINT UNSIGNED NOT NULL,
  `motivo` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `validacion_titulaciones_documento_titulacion_id_foreign` (`documento_titulacion_id` ASC) VISIBLE,
  CONSTRAINT `validacion_titulaciones_documento_titulacion_id_foreign`
    FOREIGN KEY (`documento_titulacion_id`)
    REFERENCES `titulacion`.`documento_titulaciones` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
