#archivo de configuración de la documentación de la API en formato YAML para pruebas de OpenAPI

openapi: 3.0.0
info:
  title: API Para la Automatización del proceso de titualción
  description: API para gestionar el proceso de titulación de los estudiantes del Tecnm.
  version: 0.0.1

servers:
  - url: http://localhost:8000/api
    description: Servidor de desarrollo local
  - url: https://api.tusitio.com/api/
    description: Servidor de local

paths:
  /usuarios:  # Cambia 'users' por 'usuarios' si usas español
    get:
      summary: Obtener lista de usuarios
      description: Retorna una lista de todos los usuarios registrados.
      responses:
        "200":
          description: Una lista JSON de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: ID del usuario
                    nombre:
                      type: string
                      description: Nombre del usuario
                    email:
                      type: string
                      format: email
                      description: Correo electrónico del usuario
  /usuarios/{id}:
    get:
      summary: Obtener un usuario específico
      description: Retorna los detalles de un usuario específico por su ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID del usuario a obtener
          schema:
            type: integer
      responses:
        "200":
          description: Detalles del usuario
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre:
                    type: string
                  email:
                    type: string
                    format: email
        "404":
          description: Usuario no encontrado
